services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infra/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: iot-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./fog/node-red:/data
    environment:
      - TZ=UTC
    depends_on:
      - mosquitto
    restart: unless-stopped

  backend:
    build:
      context: ./cloud-backend
      dockerfile: Dockerfile
    container_name: iot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./cloud-backend/data:/app/data
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_WS_PORT=9001
      - PORT=8000
      - DB_URL=sqlite:///data/app.db
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: iot-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

  temp-sensor:
    image: python:3.11-slim
    container_name: iot-temp-sensor
    working_dir: /app/edge/sensors
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    volumes:
      - ./edge:/app/edge:ro
    depends_on:
      - mosquitto
    command: >
      sh -c "pip install --no-cache-dir -r /app/edge/sensors/requirements.txt
      && python temp_sensor.py"
    restart: unless-stopped

  humidity-sensor:
    image: python:3.11-slim
    container_name: iot-humidity-sensor
    working_dir: /app/edge/sensors
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    volumes:
      - ./edge:/app/edge:ro
    depends_on:
      - mosquitto
    command: >
      sh -c "pip install --no-cache-dir -r /app/edge/sensors/requirements.txt
      && python humidity_sensor.py"
    restart: unless-stopped

  luminosity-sensor:
    image: python:3.11-slim
    container_name: iot-luminosity-sensor
    working_dir: /app/edge/sensors
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    volumes:
      - ./edge:/app/edge:ro
    depends_on:
      - mosquitto
    command: >
      sh -c "pip install --no-cache-dir -r /app/edge/sensors/requirements.txt
      && python luminosity_sensor.py"
    restart: unless-stopped

volumes:
  mosquitto_data:
  nodered_data:
  backend_data: